import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useCharacters } from "@/hooks/use-characters";
import { Carousel } from "@/components/carousel";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { characters, fetchCharacters } = useCharacters();

  return (
    <div>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <main>
        <Carousel characters={characters} />
      </main>
    </div>
  );
}
